CREATE TABLE users (
	id SERIAL NOT NULL PRIMARY KEY,
	login VARCHAR(255) NOT NULL UNIQUE,
	pw_hash VARCHAR(255) NOT NULL,
	status VARCHAR(8) DEFAULT 'offline'
);

CREATE TABLE msgdata (
	id SERIAL NOT NULL PRIMARY KEY,
	sender_id INTEGER NOT NULL REFERENCES users(id)
		ON DELETE CASCADE ON UPDATE CASCADE,
	recipient_id INTEGER REFERENCES users(id)
		ON DELETE CASCADE ON UPDATE CASCADE,
	content TEXT,
	received_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
